[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_ota.csv
lib_deps =
    bblanchon/ArduinoJson@^7.2.1
    knolleary/PubSubClient@^2.8
build_flags =
    -DAPP_VERSION=\"1.1.0-mqtt\"
    -DDEFAULT_POWER_GPIO=2
    -DWIFI_CONNECT_TIMEOUT_MS=15000
